### ISSUE TITLE
feature roadmap?

### ISSUE THREAD

**Issue by vtolstov** [heimdalr/dag#1]
did you mind to add ordered output and graph traversal from top to bottom?

**Comment by sebogh** [comment]
@vtolstov see latest release (v0.9.9), which added:

- [`GetOrderedAncestors()`](https://godoc.org/github.com/heimdalr/dag#DAG.GetOrderedAncestors)
- [`GetOrderedDescendants()`](https://godoc.org/github.com/heimdalr/dag#DAG.GetOrderedDescendants)
- [`AncestorsWalker()`](https://godoc.org/github.com/heimdalr/dag#DAG.AncestorsWalker)
- [`DescendantsWalker()`](https://godoc.org/github.com/heimdalr/dag#DAG.DescendantsWalker)

Something like that?

**Comment by vtolstov** [comment]
yes looks good, thanks! i'm try to use you library instead of terraform/dag .
What you think about adding method to get vertex from dag? I don't known about how api looks, main thing - if my vertex is the interface that have method Name() string or ID() string i want to get such vertex from dag and get ancestors from it.
With terraform/dag i need to have separate map[string]interface{} for all vertices and get vertex from map by name and after that iterate dag

**Comment by vtolstov** [comment]
also, how to deal with nested dag? so if vertex is the another dag ? This will be useful too

**Comment by sebogh** [comment]
> What you think about adding method to get vertex from dag? I don't known about how api looks, main thing - if my vertex is the interface that have method Name() string or ID() string i want to get such vertex from dag and get ancestors from it.
> With terraform/dag i need to have separate map[string]interface{} for all vertices and get vertex from map by name and after that iterate dag

I can see the use of such a method. However adding it would make assertion about the vertices, which is from the DAG point of view unnecessary and kind of a duplicate to the interface. In the end the DAG would implement a mapping on the back of potentially unnecessary conversions. 

Thus I suggest to implement this mapping outside of the DAG.

**Comment by sebogh** [comment]
> also, how to deal with nested dag? so if vertex is the another dag ? This will be useful too

If I understand you correct, then you talk about a recursive data-structure. Such is interesting but likely terribly slow.

**Comment by vtolstov** [comment]
thanks, but if vertex does not have uniq names, what is the use-case?

**Comment by sebogh** [comment]
see latest release (v0.9.10), which added `GetVertex()`

**Comment by vtolstov** [comment]
greate! big thanks! last question do you plan to create transitive reduction function of dag?

**Comment by vtolstov** [comment]
and also i need Validate() error on dag. to check that dag has no loops or something other errors.

**Comment by vtolstov** [comment]
with transitive reduction issue may be related to it https://github.com/heimdalr/dag/issues/2

**Comment by sebogh** [comment]
> and also i need Validate() error on dag. to check that dag has no loops or something other errors.

when adding edges, loops are being checked

**Comment by sebogh** [comment]
> greate! big thanks! last question do you plan to create transitive reduction function of dag?

Currently I don't have a use-case for it, yet I'll look at it.
