### ISSUE TITLE
transitive reduction

### ISSUE THREAD

**Issue by vtolstov** [heimdalr/dag#2]
i have vertices:
AccountCreate ProjectCreate NetworkCreate ContactCreate AuthzCreate MailSend
edges looks like
AccountCreate => ProjectCreate
AccountCreate => NetworkCreate
AccountCreate => ContactCreate
AccountCreate => AuthzCreate
AccountCreate => MailSend

ProjectCreate => MailSend
NetworkCreate => MailSend
ContactCreate => MailSend
AuthzCreate => MailSend

with terraform/dag package i have proper ordering
2020/01/24 01:29:52 step AccountCreate
2020/01/24 01:29:52 step ProjectCreate
2020/01/24 01:29:52 step NetworkCreate
2020/01/24 01:29:52 step ContactCreate
2020/01/24 01:29:53 step AuthzCreate
2020/01/24 01:29:53 step MailSend

with this package i have sometimes proper ordering and sometimes not:
2020/01/24 01:35:08 step AccountCreate
2020/01/24 01:35:08 step NetworkCreate
2020/01/24 01:35:08 step AuthzCreate
2020/01/24 01:35:08 step MailSend
2020/01/24 01:35:08 step ContactCreate
2020/01/24 01:35:08 step ProjectCreate

as i understand this because terraform/dag have ability to do transitive reduction
can you add it?

**Comment by sebogh** [comment]
You are right, the difference is likely due to transitive reduction.

> can you add it?

I'll look into it. Thus, maybe. 

I can see there may be use for it in some scenarios in others, however, you don't want that.

**Comment by vtolstov** [comment]
I think that this is must be dedicated func, so if you need it, call it.

**Comment by vtolstov** [comment]
@sebogh do you have time to look at transitive reduction and add it to this package?

**Comment by sebogh** [comment]
@vtolstov yes I will.

**Comment by sebogh** [comment]
> I think that this is must be dedicated func, so if you need it, call it.

yes, it will be a function returning a new DAG

**Comment by vtolstov** [comment]
Why not modify current dag? As transitive reduction saves all needed edges between vertex two dags is equal. What you think?

**Comment by vtolstov** [comment]
> Based on the descendants cache (effectively a transitive closure), I'll follow:

Great! I'm already switched to you package to work with dag (instead of terraform/dag package) and interface of you package is very good and easy. Thanks!

When you can provide some first steps for transitive reduction?

**Comment by sebogh** [comment]
> Why not modify current dag? As transitive reduction saves all needed edges between vertex two dags is equal. What you think?

If you want to travel from Moscow Kursky railway station to Spasskaya Tower would you like to go through Kamchatka?

**Comment by vtolstov** [comment]
Interesting question, but if all stations that present on trip visited, i think that this ok:)

**Comment by sebogh** [comment]
Transitive reduction would remove the edge (A,B), if there was also the edges (A,C) and (C,B). Thus, the reduced graph would no longer contain the info that there is quick way from Moscow Kursky railway station to Spasskaya Tower.

Never the less since it is easier to modify the existing graph, I'll simply modify the existing one. ;)

**Comment by vtolstov** [comment]
yes, ok. i'm waiting for you to test=)

**Comment by sebogh** [comment]
see latest release (v0.9.11), which added:

- [`ReduceTransitively()`](https://godoc.org/github.com/heimdalr/dag#DAG.ReduceTransitively) and 
- [`IsEdge()`](https://godoc.org/github.com/heimdalr/dag#DAG.IsEdge)

**Comment by vtolstov** [comment]
Thanks, why you mention about big memory usage? If i have 100 vertex does reduction cost many cpu?

**Comment by vtolstov** [comment]
thanks! very cool, now all fine.
Can you suggest me how the best create saga pattern using this dag package?
Now i simply create two dags - one for forward execution, and another for compensate. Does it possible to have all in one dag and dynamically decide what branch to use?

**Comment by sebogh** [comment]
> Can you suggest me how the best create saga pattern using this dag package?

Don't know.

**Comment by sebogh** [comment]
> thanks! very cool, now all fine.

fine.
