### ISSUE TITLE
Support non comparable type in vertex

### ISSUE THREAD

**Issue by rizerkrof** [heimdalr/dag#33]
I just started using your awesome dag lib but it doesn't support non-comparable types in the vertex payload. 

Indeed the list of vertices uses a map with the vertex payload as key. This implementation forces the payload to contain only comparable types at the risk of throwing this kind of error: `panic: runtime error: hash of unhashable type ...`

I suggest adding an option allowing to override the vertex map key by a custom value (so that the new value only contains comparable types).

What do you think?

Thank you! :)

**Comment by GabrielTruong** [comment]
That would be an awesome feature and would help me on a personal project !

**Comment by sebogh** [comment]
@rizerkrof thanks! 

In case you wonder, I merged the PR but a release action shot to early. Thus I retracted the [v1.4.1](https://github.com/heimdalr/dag/releases/tag/v1.4.1) release and have your contribution available via the latest [v1.5.0](https://github.com/heimdalr/dag/releases/tag/v1.5.0). Thank you.
