### ISSUE TITLE
 AddEdge Implementation

### ISSUE THREAD

**Issue by vtolstov** [heimdalr/dag#4]
i'm profile my app when using this package, and found
why vertex added when adding adge? this is some sugar ? I mean that most of the time user must add vertex and after that add adge. This api simplify stuff by not adding vertex, but operate only via AddEdge, but i think this is not right api usage.

```                                          
// ensure vertices                        
if !d.vertices[src] {                     
  err := d.AddVertex(src)                 
  if err != nil {                         
    return err                            
  }                                       
}                                         
if !d.vertices[dst] {                     
  err := d.AddVertex(dst)                 
  if err != nil {                         
    return err                            
  }                                       
}                                         
```

**Comment by sebogh** [comment]
You can always add the vertex in advance. Still, in order ensure consistency AddEdge() needs to always check, if vertices exist.

**Comment by vtolstov** [comment]
ok.
