### ISSUE TITLE
Change Vertex interface method name

### ISSUE THREAD

**Issue by JJBordy** [heimdalr/dag#7]
The compiler complains that the Vertex interface is not named by Go conventions...

`Id() string`

should be 

`ID() string`

nothing super urgent, but to keep in mind...

**Comment by seboghpub** [comment]
Thanks for the hint. 

However, I'll leave as is (at least for now) not to introduce a breaking change.

**Comment by sebogh** [comment]
With [v1.0.0](https://github.com/heimdalr/dag/releases/tag/v1.0.0) the API has changed in many aspects. As part of this the above was addressed.
